# Generated by Django 5.0.4 on 2024-04-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('Runs', models.IntegerField()),
                ('centuries', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('avg', models.FloatField()),
                ('Highest_score', models.IntegerField()),
                ('strike_rate', models.FloatField()),
            ],
        ),
    ]
